name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  simple_animations: ^1.3.4
  animated_background: ^1.0.5
  flare_flutter: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: PressStart2P
      fonts:
        - asset: third_party/PressStart2P-Regular.ttf
    - family: Digital
      fonts:
        - asset: third_party/digital-7.ttf
    - family: Loopy
      fonts:
        - asset: third_party/LOOPY___.ttf
    - family: TTBB
      fonts:
        - asset: third_party/TickingTimebombBB.ttf
    - family: Trs_Million
      fonts:
        - asset: third_party/trs-million_rg.ttf
  assets:
    - assets/horos/
    - assets/flares/pulsing_white.flr
    - assets/flares/pulsing_bg.flr


